# -*- coding: utf-8 -*-
"""Vehicle-Object-Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A8b2ei0CB5xgaoUl0b_iiVYP0hhCju-g
"""

# Step 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')
# Step 2: Install YOLOv8 & Roboflow
!pip install ultralytics roboflow --quiet
# Step 3: Import Libraries
from roboflow import Roboflow
from ultralytics import YOLO
import os
# Step 4: Download Dataset from Roboflow
rf = Roboflow(api_key="")
project = rf.workspace("").project("")
version = project.version(4)
dataset = version.download("yolov8-obb")
# :white_check_mark: Fix: Get dataset YAML file correctly
dataset_yaml = dataset.location + "/data.yaml"
# Step 5: Train YOLOv8 Model (50 epochs)
model = YOLO("yolov8m.pt")
model.train(
    data=dataset_yaml,
    epochs=500,
    imgsz=640,
    batch=16,
    cache=True,
    device="cuda"
)
# Step 6: Save Trained Model to Google Drive
model_path = "/content/runs/detect/train/weights/best.pt"
drive_model_path = "/content/drive/MyDrive/best.pt"
if os.path.exists(model_path):
    !cp {model_path} {drive_model_path}
    print(f":white_check_mark: Model saved to Google Drive: {drive_model_path}")
else:
    print(":x: Training failed or model not found.")